-- ALTERAÇÕES EM ASSENTOS_SESSAO

-- Adiciona tipo do assento (COMUM, PNE, VIP)
ALTER TABLE assentos_sessao
    ADD COLUMN tipo VARCHAR(10) NOT NULL DEFAULT 'COMUM';

-- Adiciona valor do ingresso para este assento na sessão
ALTER TABLE assentos_sessao
    ADD COLUMN valor NUMERIC(10, 2) NOT NULL DEFAULT 25.00;

-- Adiciona status do assento (substitui o boolean ocupado)
ALTER TABLE assentos_sessao
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'DISPONIVEL';

-- Migra dados existentes do campo ocupado para o novo status
UPDATE assentos_sessao SET status = 'OCUPADO' WHERE ocupado = TRUE;

-- Remove a coluna legada
ALTER TABLE assentos_sessao DROP COLUMN ocupado;

-- Adiciona constraints de integridade
ALTER TABLE assentos_sessao
    ADD CONSTRAINT ck_assentos_tipo
        CHECK (tipo IN ('COMUM', 'PNE', 'VIP'));

ALTER TABLE assentos_sessao
    ADD CONSTRAINT ck_assentos_status
        CHECK (status IN ('DISPONIVEL', 'OCUPADO', 'VENDIDO'));

ALTER TABLE assentos_sessao
    ADD CONSTRAINT ck_assentos_valor
        CHECK (valor >= 0);

CREATE INDEX idx_assentos_sessao_status ON assentos_sessao(status);
CREATE INDEX idx_assentos_sessao_tipo   ON assentos_sessao(tipo);


-- PEDIDOS
CREATE TABLE pedidos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sessao_id       BIGINT         NOT NULL,
    user_id         BIGINT,
    valor_total     NUMERIC(10, 2) NOT NULL,
    metodo          VARCHAR(50)    NOT NULL,
    status          VARCHAR(20)    NOT NULL DEFAULT 'PENDENTE',
    ingresso_id     VARCHAR(50)    UNIQUE,
    criado_em       TIMESTAMP      NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_pedidos_sessao
        FOREIGN KEY (sessao_id) REFERENCES sessoes(id),

    CONSTRAINT fk_pedidos_user
        FOREIGN KEY (user_id) REFERENCES users(id),

    CONSTRAINT ck_pedidos_status
        CHECK (status IN ('PENDENTE', 'PAGO', 'CANCELADO')),

    CONSTRAINT ck_pedidos_metodo
        CHECK (metodo IN ('CARTAO_CREDITO', 'CARTAO_DEBITO', 'PIX', 'DINHEIRO')),

    CONSTRAINT ck_pedidos_valor
        CHECK (valor_total >= 0)
);

CREATE INDEX idx_pedidos_sessao_id  ON pedidos(sessao_id);
CREATE INDEX idx_pedidos_user_id    ON pedidos(user_id);
CREATE INDEX idx_pedidos_status     ON pedidos(status);
CREATE INDEX idx_pedidos_criado_em  ON pedidos(criado_em);


-- PEDIDO_ASSENTOS
CREATE TABLE pedido_assentos (
    pedido_id   BIGINT NOT NULL,
    assento_id  BIGINT NOT NULL,

    CONSTRAINT pk_pedido_assentos
        PRIMARY KEY (pedido_id, assento_id),

    CONSTRAINT fk_pedido_assentos_pedido
        FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE,

    CONSTRAINT fk_pedido_assentos_assento
        FOREIGN KEY (assento_id) REFERENCES assentos_sessao(id)
);
